### ISSUE TITLE
[Tutorial] Migrate from reason-react to @rescript/react

### ISSUE THREAD

**Issue by gargakshit** [dusty-phillips/rescript-react-intro#1]
`@rescript/react` is out, so I request you to migrate your tutorials to use the same. A reference for the same is provided in the [rescript docs](https://rescript-lang.org/docs/react/latest/installation). Thanks for the awesome tutorials.

**Comment by dusty-phillips** [comment]
Awesome!! I've been waiting for that. :-)

**Comment by dusty-phillips** [comment]
Should be all fixed up now. I had to remove the links to individual git commits because it became too much of a headache to maintain with all the rebasing going on.

I'm not 100% certain the initialization step works because it seems like rescript-react is failing to accept rescript 9.0.0. I added a npm install --force to make it all work, but obviously that shouldn't always be necessary.

**Comment by gargakshit** [comment]
> Should be all fixed up now. I had to remove the links to individual git commits because it became too much of a headache to maintain with all the rebasing going on.
> 
> I'm not 100% certain the initialization step works because it seems like rescript-react is failing to accept rescript 9.0.0. I added a npm install --force to make it all work, but obviously that shouldn't always be necessary.

I was using `yarn` and I didn't face such issue.
Thanks for updating though :)
